version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: store-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: basic-auth-store
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - store-network

  backend:
    image: eclipse-temurin:21-jdk
    container_name: store-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend/target:/app
    working_dir: /app
    command: java -jar backend-0.0.1-SNAPSHOT.jar
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql
    networks:
      - store-network

  frontend:
    image: nginx:alpine
    container_name: store-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    volumes:
      - ./frontend/dist/frontend/browser:/usr/share/nginx/html:ro
    networks:
      - store-network

volumes:
  db-data:

networks:
  store-network:
    driver: bridge
